// Copyright 2026 Phillip Cloud
// Licensed under the Apache License, Version 2.0

package webapi

import (
	"encoding/json"
	"errors"
	"net/http"

	"github.com/micasa-dev/micasa/internal/data"
	"gorm.io/gorm"
)

func (h *handlers) listAppliances(w http.ResponseWriter, _ *http.Request) {
	items, err := h.store.ListAppliances(false)
	if err != nil {
		h.log.Error("list appliances", "error", err)
		writeError(w, http.StatusInternalServerError, "failed to list appliances")
		return
	}
	writeJSON(w, http.StatusOK, items)
}

func (h *handlers) getAppliance(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	item, err := h.store.GetAppliance(id)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			writeError(w, http.StatusNotFound, "appliance not found")
			return
		}
		h.log.Error("get appliance", "error", err, "id", id)
		writeError(w, http.StatusInternalServerError, "failed to get appliance")
		return
	}
	writeJSON(w, http.StatusOK, item)
}

func (h *handlers) createAppliance(w http.ResponseWriter, r *http.Request) {
	var item data.Appliance
	if err := json.NewDecoder(r.Body).Decode(&item); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	// ID is generated by the model's BeforeCreate hook; ignore any client value.
	item.ID = ""
	if err := h.store.CreateAppliance(&item); err != nil {
		h.log.Error("create appliance", "error", err)
		writeError(w, http.StatusUnprocessableEntity, err.Error())
		return
	}
	writeJSON(w, http.StatusCreated, item)
}

func (h *handlers) updateAppliance(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	var item data.Appliance
	if err := json.NewDecoder(r.Body).Decode(&item); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	item.ID = id
	if err := h.store.UpdateAppliance(item); err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			writeError(w, http.StatusNotFound, "appliance not found")
			return
		}
		h.log.Error("update appliance", "error", err, "id", id)
		writeError(w, http.StatusUnprocessableEntity, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, item)
}

func (h *handlers) deleteAppliance(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if err := h.store.DeleteAppliance(id); err != nil {
		// DeleteAppliance rejects deletion when dependent maintenance items or
		// incidents exist; surface that as a conflict with its message.
		h.log.Error("delete appliance", "error", err, "id", id)
		writeError(w, http.StatusConflict, err.Error())
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
