// Copyright 2026 Phillip Cloud
// Licensed under the Apache License, Version 2.0

package webapi

import (
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"

	"gorm.io/gorm"
)

// Handler factories for one entity's CRUD routes. Handlers must only call
// Store methods (business logic stays in internal/data), so each factory
// takes a thin closure over the corresponding method. Entities with
// non-standard signatures (quotes, service logs) compose these directly.

func listHandler[T any](log *slog.Logger, name string, list func() ([]T, error)) http.HandlerFunc {
	return func(w http.ResponseWriter, _ *http.Request) {
		items, err := list()
		if err != nil {
			log.Error("list "+name, "error", err)
			writeError(w, http.StatusInternalServerError, "failed to list "+name)
			return
		}
		writeJSON(w, http.StatusOK, items)
	}
}

func getHandler[T any](log *slog.Logger, name string, get func(id string) (T, error)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		id := r.PathValue("id")
		item, err := get(id)
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				writeError(w, http.StatusNotFound, name+" not found")
				return
			}
			log.Error("get "+name, "error", err, "id", id)
			writeError(w, http.StatusInternalServerError, "failed to get "+name)
			return
		}
		writeJSON(w, http.StatusOK, item)
	}
}

// createHandler decodes T, clears the client-supplied ID (IDs are
// server-generated by BeforeCreate hooks), and persists.
func createHandler[T any](log *slog.Logger, name string, setID func(*T, string), create func(*T) error) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var item T
		if err := json.NewDecoder(r.Body).Decode(&item); err != nil {
			writeError(w, http.StatusBadRequest, "invalid JSON body")
			return
		}
		setID(&item, "")
		if err := create(&item); err != nil {
			log.Error("create "+name, "error", err)
			writeError(w, http.StatusUnprocessableEntity, err.Error())
			return
		}
		writeJSON(w, http.StatusCreated, item)
	}
}

func updateHandler[T any](log *slog.Logger, name string, setID func(*T, string), update func(T) error) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		id := r.PathValue("id")
		var item T
		if err := json.NewDecoder(r.Body).Decode(&item); err != nil {
			writeError(w, http.StatusBadRequest, "invalid JSON body")
			return
		}
		setID(&item, id)
		if err := update(item); err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				writeError(w, http.StatusNotFound, name+" not found")
				return
			}
			log.Error("update "+name, "error", err, "id", id)
			writeError(w, http.StatusUnprocessableEntity, err.Error())
			return
		}
		writeJSON(w, http.StatusOK, item)
	}
}

func deleteHandler(log *slog.Logger, name string, remove func(id string) error) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		id := r.PathValue("id")
		if err := remove(id); err != nil {
			// Store delete methods reject deletion while dependent records
			// exist; surface that as a conflict with the store's message.
			log.Error("delete "+name, "error", err, "id", id)
			writeError(w, http.StatusConflict, err.Error())
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}

// entityOps bundles standard CRUD closures for registerEntity.
type entityOps[T any] struct {
	list   func() ([]T, error)
	get    func(id string) (T, error)
	create func(item *T) error
	update func(item T) error
	remove func(id string) error
	setID  func(item *T, id string)
}

// registerEntity wires the five standard routes under basePath.
func registerEntity[T any](mux *http.ServeMux, log *slog.Logger, basePath, name string, ops entityOps[T]) {
	mux.HandleFunc("GET "+basePath, listHandler(log, name, ops.list))
	mux.HandleFunc("GET "+basePath+"/{id}", getHandler(log, name, ops.get))
	mux.HandleFunc("POST "+basePath, createHandler(log, name, ops.setID, ops.create))
	mux.HandleFunc("PUT "+basePath+"/{id}", updateHandler(log, name, ops.setID, ops.update))
	mux.HandleFunc("DELETE "+basePath+"/{id}", deleteHandler(log, name, ops.remove))
}
