// Copyright 2026 Phillip Cloud
// Licensed under the Apache License, Version 2.0

// Code generated by genmeta; DO NOT EDIT.

package data

// Table name constants derived from GORM model structs.
const (
	TableAppliances            = "appliances"
	TableChatInputs            = "chat_inputs"
	TableDeletionRecords       = "deletion_records"
	TableDocuments             = "documents"
	TableFloorPlans            = "floor_plans"
	TableHouseProfiles         = "house_profiles"
	TableIncidents             = "incidents"
	TableMaintenanceCategories = "maintenance_categories"
	TableMaintenanceItems      = "maintenance_items"
	TablePlanMarkers           = "plan_markers"
	TableProjectTypes          = "project_types"
	TableProjects              = "projects"
	TableQuotes                = "quotes"
	TableRooms                 = "rooms"
	TableServiceLogEntries     = "service_log_entries"
	TableSettings              = "settings"
	TableSyncDevices           = "sync_devices"
	TableSyncOplogEntries      = "sync_oplog_entries"
	TableVendors               = "vendors"
)

// Column name constants derived from GORM model structs.
const (
	ColActualCents       = "actual_cents"
	ColAddressLine1      = "address_line1"
	ColAddressLine2      = "address_line2"
	ColApplianceID       = "appliance_id"
	ColAppliedAt         = "applied_at"
	ColBasementType      = "basement_type"
	ColBathrooms         = "bathrooms"
	ColBedrooms          = "bedrooms"
	ColBrand             = "brand"
	ColBudgetCents       = "budget_cents"
	ColCategoryID        = "category_id"
	ColChecksumSHA256    = "sha256"
	ColCity              = "city"
	ColContactName       = "contact_name"
	ColCoolingType       = "cooling_type"
	ColCostCents         = "cost_cents"
	ColCreatedAt         = "created_at"
	ColData              = "data"
	ColDateNoticed       = "date_noticed"
	ColDateResolved      = "date_resolved"
	ColDeletedAt         = "deleted_at"
	ColDescription       = "description"
	ColDeviceID          = "device_id"
	ColDueDate           = "due_date"
	ColEmail             = "email"
	ColEndDate           = "end_date"
	ColEntity            = "entity"
	ColEntityID          = "entity_id"
	ColEntityKind        = "entity_kind"
	ColExteriorType      = "exterior_type"
	ColExtractData       = "ocr_data"
	ColExtractedText     = "extracted_text"
	ColExtractionModel   = "extraction_model"
	ColExtractionOps     = "extraction_ops"
	ColFileName          = "file_name"
	ColFloor             = "floor"
	ColFloorPlanID       = "floor_plan_id"
	ColFoundationType    = "foundation_type"
	ColHAEntity          = "ha_entity"
	ColHOAFeeCents       = "hoa_fee_cents"
	ColHOAName           = "hoa_name"
	ColHeatingType       = "heating_type"
	ColHouseholdID       = "household_id"
	ColID                = "id"
	ColInput             = "input"
	ColInsuranceCarrier  = "insurance_carrier"
	ColInsurancePolicy   = "insurance_policy"
	ColInsuranceRenewal  = "insurance_renewal"
	ColIntervalMonths    = "interval_months"
	ColKey               = "key"
	ColKind              = "kind"
	ColLabel             = "label"
	ColLaborCents        = "labor_cents"
	ColLastSeq           = "last_seq"
	ColLastServicedAt    = "last_serviced_at"
	ColLocale            = "locale"
	ColLocation          = "location"
	ColLotSquareFeet     = "lot_square_feet"
	ColMIMEType          = "mime_type"
	ColMaintenanceItemID = "maintenance_item_id"
	ColManualText        = "manual_text"
	ColManualURL         = "manual_url"
	ColMaterialsCents    = "materials_cents"
	ColModelNumber       = "model_number"
	ColName              = "name"
	ColNickname          = "nickname"
	ColNotes             = "notes"
	ColOpType            = "op_type"
	ColOtherCents        = "other_cents"
	ColParkingType       = "parking_type"
	ColPayload           = "payload"
	ColPhone             = "phone"
	ColPostalCode        = "postal_code"
	ColPreviousStatus    = "previous_status"
	ColProjectID         = "project_id"
	ColProjectTypeID     = "project_type_id"
	ColPropertyTaxCents  = "property_tax_cents"
	ColPurchaseDate      = "purchase_date"
	ColReceivedDate      = "received_date"
	ColRelayURL          = "relay_url"
	ColRestoredAt        = "restored_at"
	ColRoofType          = "roof_type"
	ColRoomID            = "room_id"
	ColRowID             = "row_id"
	ColSeason            = "season"
	ColSerialNumber      = "serial_number"
	ColServicedAt        = "serviced_at"
	ColSeverity          = "severity"
	ColSewerType         = "sewer_type"
	ColSizeBytes         = "size_bytes"
	ColSquareFeet        = "square_feet"
	ColStartDate         = "start_date"
	ColState             = "state"
	ColStatus            = "status"
	ColSyncedAt          = "synced_at"
	ColTableName         = "table_name"
	ColTargetID          = "target_id"
	ColTitle             = "title"
	ColTotalCents        = "total_cents"
	ColUpdatedAt         = "updated_at"
	ColValue             = "value"
	ColVendorID          = "vendor_id"
	ColWarrantyExpiry    = "warranty_expiry"
	ColWaterSource       = "water_source"
	ColWebsite           = "website"
	ColWiringType        = "wiring_type"
	ColX                 = "x"
	ColY                 = "y"
	ColYearBuilt         = "year_built"
)

// Models returns a pointer to every GORM model struct in source order.
// Used by AutoMigrate and FK introspection.
func Models() []any {
	return []any{
		&HouseProfile{},
		&ProjectType{},
		&Vendor{},
		&Project{},
		&Quote{},
		&MaintenanceCategory{},
		&Appliance{},
		&MaintenanceItem{},
		&Incident{},
		&ServiceLogEntry{},
		&Document{},
		&DeletionRecord{},
		&Setting{},
		&ChatInput{},
		&SyncOplogEntry{},
		&SyncDevice{},
		&Room{},
		&FloorPlan{},
		&PlanMarker{},
	}
}

// metaColumn describes a single DB column's name and JSON Schema type.
// Used by the extraction system to derive column definitions from models.
type metaColumn struct {
	Name     string
	JSONType string // "string" or "integer"
}

// TableExtractColumns maps each table to its extractable columns.
// Excludes primary keys, auto-managed timestamps, soft-delete markers,
// GORM association fields, and binary data columns.
var TableExtractColumns = map[string][]metaColumn{
	TableAppliances: {
		{Name: "name", JSONType: "string"},
		{Name: "brand", JSONType: "string"},
		{Name: "model_number", JSONType: "string"},
		{Name: "serial_number", JSONType: "string"},
		{Name: "location", JSONType: "string"},
		{Name: "cost_cents", JSONType: "integer"},
		{Name: "notes", JSONType: "string"},
	},
	TableChatInputs: {
		{Name: "input", JSONType: "string"},
	},
	TableDeletionRecords: {
		{Name: "entity", JSONType: "string"},
		{Name: "target_id", JSONType: "string"},
		{Name: "restored_at", JSONType: "string"},
	},
	TableDocuments: {
		{Name: "title", JSONType: "string"},
		{Name: "file_name", JSONType: "string"},
		{Name: "entity_kind", JSONType: "string"},
		{Name: "entity_id", JSONType: "string"},
		{Name: "notes", JSONType: "string"},
	},
	TableFloorPlans: {
		{Name: "name", JSONType: "string"},
		{Name: "floor", JSONType: "integer"},
	},
	TableHouseProfiles: {
		{Name: "nickname", JSONType: "string"},
		{Name: "address_line1", JSONType: "string"},
		{Name: "address_line2", JSONType: "string"},
		{Name: "city", JSONType: "string"},
		{Name: "state", JSONType: "string"},
		{Name: "postal_code", JSONType: "string"},
		{Name: "year_built", JSONType: "integer"},
		{Name: "square_feet", JSONType: "integer"},
		{Name: "lot_square_feet", JSONType: "integer"},
		{Name: "bedrooms", JSONType: "integer"},
		{Name: "bathrooms", JSONType: "integer"},
		{Name: "foundation_type", JSONType: "string"},
		{Name: "wiring_type", JSONType: "string"},
		{Name: "roof_type", JSONType: "string"},
		{Name: "exterior_type", JSONType: "string"},
		{Name: "heating_type", JSONType: "string"},
		{Name: "cooling_type", JSONType: "string"},
		{Name: "water_source", JSONType: "string"},
		{Name: "sewer_type", JSONType: "string"},
		{Name: "parking_type", JSONType: "string"},
		{Name: "basement_type", JSONType: "string"},
		{Name: "insurance_carrier", JSONType: "string"},
		{Name: "insurance_policy", JSONType: "string"},
		{Name: "insurance_renewal", JSONType: "string"},
		{Name: "property_tax_cents", JSONType: "integer"},
		{Name: "hoa_name", JSONType: "string"},
		{Name: "hoa_fee_cents", JSONType: "integer"},
	},
	TableIncidents: {
		{Name: "title", JSONType: "string"},
		{Name: "description", JSONType: "string"},
		{Name: "status", JSONType: "string"},
		{Name: "severity", JSONType: "string"},
		{Name: "date_noticed", JSONType: "string"},
		{Name: "location", JSONType: "string"},
		{Name: "cost_cents", JSONType: "integer"},
		{Name: "appliance_id", JSONType: "string"},
		{Name: "vendor_id", JSONType: "string"},
		{Name: "notes", JSONType: "string"},
	},
	TableMaintenanceCategories: {
		{Name: "name", JSONType: "string"},
	},
	TableMaintenanceItems: {
		{Name: "name", JSONType: "string"},
		{Name: "category_id", JSONType: "string"},
		{Name: "appliance_id", JSONType: "string"},
		{Name: "season", JSONType: "string"},
		{Name: "interval_months", JSONType: "integer"},
		{Name: "notes", JSONType: "string"},
		{Name: "cost_cents", JSONType: "integer"},
	},
	TablePlanMarkers: {
		{Name: "floor_plan_id", JSONType: "string"},
		{Name: "x", JSONType: "integer"},
		{Name: "y", JSONType: "integer"},
		{Name: "label", JSONType: "string"},
		{Name: "kind", JSONType: "string"},
		{Name: "room_id", JSONType: "string"},
		{Name: "appliance_id", JSONType: "string"},
		{Name: "ha_entity", JSONType: "string"},
	},
	TableProjectTypes: {
		{Name: "name", JSONType: "string"},
	},
	TableProjects: {
		{Name: "title", JSONType: "string"},
		{Name: "project_type_id", JSONType: "string"},
		{Name: "status", JSONType: "string"},
		{Name: "description", JSONType: "string"},
		{Name: "budget_cents", JSONType: "integer"},
	},
	TableQuotes: {
		{Name: "project_id", JSONType: "string"},
		{Name: "vendor_id", JSONType: "string"},
		{Name: "total_cents", JSONType: "integer"},
		{Name: "labor_cents", JSONType: "integer"},
		{Name: "materials_cents", JSONType: "integer"},
		{Name: "notes", JSONType: "string"},
	},
	TableRooms: {
		{Name: "name", JSONType: "string"},
		{Name: "floor", JSONType: "integer"},
		{Name: "notes", JSONType: "string"},
	},
	TableServiceLogEntries: {
		{Name: "maintenance_item_id", JSONType: "string"},
		{Name: "serviced_at", JSONType: "string"},
		{Name: "vendor_id", JSONType: "string"},
		{Name: "cost_cents", JSONType: "integer"},
		{Name: "notes", JSONType: "string"},
	},
	TableSettings: {
		{Name: "key", JSONType: "string"},
		{Name: "value", JSONType: "string"},
	},
	TableSyncDevices: {
		{Name: "name", JSONType: "string"},
		{Name: "household_id", JSONType: "string"},
		{Name: "relay_url", JSONType: "string"},
		{Name: "last_seq", JSONType: "integer"},
	},
	TableSyncOplogEntries: {
		{Name: "table_name", JSONType: "string"},
		{Name: "row_id", JSONType: "string"},
		{Name: "op_type", JSONType: "string"},
		{Name: "payload", JSONType: "string"},
		{Name: "device_id", JSONType: "string"},
		{Name: "applied_at", JSONType: "string"},
		{Name: "synced_at", JSONType: "string"},
	},
	TableVendors: {
		{Name: "name", JSONType: "string"},
		{Name: "contact_name", JSONType: "string"},
		{Name: "email", JSONType: "string"},
		{Name: "phone", JSONType: "string"},
		{Name: "website", JSONType: "string"},
		{Name: "notes", JSONType: "string"},
		{Name: "locale", JSONType: "string"},
	},
}
